# Generated by Django 4.1.3 on 2022-12-14 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tzapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecamionrecepcionleche',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzapp.operador'),
        ),
        migrations.AlterField(
            model_name='detallecamionrecepcionleche',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzapp.camion'),
        ),
        migrations.AlterField(
            model_name='detallecamionrecepcionleche',
            name='recorrido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzapp.recorrido'),
        ),
        migrations.AlterField(
            model_name='detalletlc',
            name='detalle_camion_recepcion_leche',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzapp.detallecamionrecepcionleche'),
        ),
        migrations.AlterField(
            model_name='detalletlc',
            name='tlc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzapp.tlc'),
        ),
    ]
