# Generated by Django 4.1.3 on 2022-12-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tzapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinsumosformulacion',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleinsumosformulacion',
            name='usuario_del_registro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
