# Generated by Django 4.1.3 on 2022-12-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tzapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_pasteurizacion',
            name='tlp',
        ),
        migrations.CreateModel(
            name='DetalleTlp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('detalle_pasteurizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzapp.detalle_pasteurizacion')),
                ('tlp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzapp.tlp')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_pasteurizacion',
            name='tlp',
            field=models.ManyToManyField(through='tzapp.DetalleTlp', to='tzapp.tlp'),
        ),
    ]
