# Generated by Django 4.1.3 on 2022-12-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tzapp', '0002_remove_detalle_pasteurizacion_tlp_detalletlp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='parametrosRepo001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_leche_guia_minimo', models.FloatField()),
                ('temperatura_leche_guia_maximo', models.FloatField()),
                ('temperatura_leche_pool_minimo', models.FloatField()),
                ('temperatura_leche_pool_maximo', models.FloatField()),
                ('temperatura_leche_salida_enfriador_minimo', models.FloatField()),
                ('temperatura_leche_salida_enfriador_maximo', models.FloatField()),
                ('acidez_minimo', models.FloatField()),
                ('acidez_maximo', models.FloatField()),
                ('ph_camion_minimo', models.FloatField()),
                ('ph_camion_maximo', models.FloatField()),
                ('prueba_minimo', models.FloatField()),
                ('prueba_maximo', models.FloatField()),
                ('mg_minimo', models.FloatField()),
                ('mg_maximo', models.FloatField()),
                ('sng_minimo', models.FloatField()),
                ('sng_maximo', models.FloatField()),
                ('st_minimo', models.FloatField()),
                ('st_maximo', models.FloatField()),
                ('proteina_minimo', models.FloatField()),
                ('proteina_maximo', models.FloatField()),
                ('densidad_minimo', models.FloatField()),
                ('densidad_maximo', models.FloatField()),
            ],
        ),
    ]
