# Generated by Django 4.1.3 on 2022-12-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tzapp', '0002_detalleinsumosformulacion_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinsumosenvasado',
            name='comentario',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='detalleinsumosenvasado',
            name='usuario_del_registro',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='materiaprimaenvasado',
            name='numero_contenedor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='materiaprimaenvasado',
            name='numero_usos',
            field=models.IntegerField(null=True),
        ),
    ]
