# Generated by Django 4.1.3 on 2022-12-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tzapp', '0003_detalleinsumosenvasado_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleRepo017',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('comentario', models.CharField(max_length=100, null=True)),
                ('usuario_del_registro', models.CharField(max_length=100, null=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzapp.operador')),
                ('orden_proceso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tzapp.ordenproceso')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEnvasado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('kilos_consumo', models.IntegerField()),
                ('lote', models.CharField(max_length=50)),
                ('fecha_elaboracion', models.DateField()),
                ('detalle_repo017', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tzapp.detallerepo017')),
            ],
        ),
    ]
