# Generated by Django 4.1.3 on 2022-12-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tzapp', '0003_parametrosrepo001'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecamionrecepcionleche',
            name='usuario_del_registro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
